#!/bin/bash

WLAN_DEVICE=wlan0

# On CentOS the device is shown as an ethernet usb device
ifconfig $WLAN_DEVICE  2> /dev/null || WLAN_DEVICE=$(ifconfig -a | egrep -o "^enp\w*u\w*")

if [ "`which iwconfig`" = "" ] ; then 
	echo "WARNING:Wireless tool not exist!"
	echo "        Please install it!"
	exit
else
	if [ `uname -r | cut -d. -f2` -eq 4 ]; then
		wpa_supplicant -B -D ipw -c wpa1.conf -i $WLAN_DEVICE
	else
	if [ `iwconfig -v |awk '{print $4}' | head -n 1` -lt  18 ] ; then
		wpa_supplicant -D ipw -c wpa1.conf -i $WLAN_DEVICE
	else
		wpa_supplicant -D wext -c wpa1.conf -i $WLAN_DEVICE
	fi

	fi
fi


